import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// ============================================
// PDF EXPORT UTILITIES
// ============================================

interface PDFExportOptions {
  title: string;
  subtitle?: string;
  data: any[];
  columns: { header: string; dataKey: string }[];
  filename: string;
  orientation?: 'portrait' | 'landscape';
}

export const exportToPDF = ({
  title,
  subtitle,
  data,
  columns,
  filename,
  orientation = 'portrait'
}: PDFExportOptions) => {
  const doc = new jsPDF(orientation, 'mm', 'a4');
  
  // Add header
  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129); // Emerald color
  doc.text(title, 14, 20);
  
  if (subtitle) {
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, 14, 28);
  }
  
  // Add metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const date = new Date().toLocaleDateString('en-PH', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  doc.text(`Generated: ${date}`, 14, subtitle ? 35 : 28);
  
  // Add table
  autoTable(doc, {
    startY: subtitle ? 40 : 33,
    head: [columns.map(col => col.header)],
    body: data.map(item => columns.map(col => item[col.dataKey] || '-')),
    theme: 'grid',
    headStyles: {
      fillColor: [16, 185, 129], // Emerald
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    }
  });
  
  // Add footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'BarangayLink V2 - Project Management System',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }
  
  doc.save(`${filename}.pdf`);
};

// ============================================
// EXCEL EXPORT UTILITIES
// ============================================

interface ExcelExportOptions {
  data: any[];
  sheetName: string;
  filename: string;
  columns?: { header: string; key: string; width?: number }[];
}

export const exportToExcel = ({
  data,
  sheetName,
  filename,
  columns
}: ExcelExportOptions) => {
  // Create workbook
  const wb = XLSX.utils.book_new();
  
  // Create worksheet
  let ws: XLSX.WorkSheet;
  
  if (columns) {
    // With custom columns
    const headers = columns.map(col => col.header);
    const rows = data.map(item => 
      columns.map(col => item[col.key] !== undefined ? item[col.key] : '-')
    );
    const wsData = [headers, ...rows];
    ws = XLSX.utils.aoa_to_sheet(wsData);
    
    // Set column widths
    ws['!cols'] = columns.map(col => ({ wch: col.width || 15 }));
  } else {
    // Auto-generate from object keys
    ws = XLSX.utils.json_to_sheet(data);
  }
  
  // Style header row
  const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_col(C) + '1';
    if (!ws[address]) continue;
    (ws[address] as any).s = {
      font: { bold: true, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "10B981" } },
      alignment: { horizontal: "center", vertical: "center" }
    };
  }
  
  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  
  // Add metadata sheet
  const metadata = [
    ['Report Information'],
    ['Generated By', 'BarangayLink V2'],
    ['Generated On', new Date().toLocaleString('en-PH')],
    ['Total Records', data.length.toString()]
  ];
  const metaWs = XLSX.utils.aoa_to_sheet(metadata);
  XLSX.utils.book_append_sheet(wb, metaWs, 'Info');
  
  // Save file
  XLSX.writeFile(wb, `${filename}.xlsx`);
};

// ============================================
// ANALYTICS EXPORT
// ============================================

export const exportAnalyticsReport = (
  analyticsData: {
    totalProjects: number;
    completedProjects: number;
    activeProjects: number;
    pendingProjects: number;
    totalBudget: number;
    completedBudget: number;
    departmentStats: any[];
    teamStats: any[];
    recentCompletions: any[];
  },
  format: 'pdf' | 'excel'
) => {
  const date = new Date().toLocaleDateString('en-PH');
  
  if (format === 'pdf') {
    const doc = new jsPDF('portrait', 'mm', 'a4');
    
    // Title
    doc.setFontSize(24);
    doc.setTextColor(16, 185, 129);
    doc.text('Analytics Report', 14, 20);
    
    // Summary
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Report Date: ${date}`, 14, 30);
    
    // Key Metrics
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Performance Indicators', 14, 45);
    
    doc.setFontSize(10);
    let y = 55;
    doc.text(`Total Projects: ${analyticsData.totalProjects}`, 20, y);
    doc.text(`Completed: ${analyticsData.completedProjects} (${((analyticsData.completedProjects / analyticsData.totalProjects) * 100).toFixed(1)}%)`, 20, y + 7);
    doc.text(`Active: ${analyticsData.activeProjects}`, 20, y + 14);
    doc.text(`Pending: ${analyticsData.pendingProjects}`, 20, y + 21);
    doc.text(`Total Budget: ₱${analyticsData.totalBudget.toLocaleString()}`, 20, y + 28);
    doc.text(`Budget Utilization: ₱${analyticsData.completedBudget.toLocaleString()} (${analyticsData.totalBudget > 0 ? ((analyticsData.completedBudget / analyticsData.totalBudget) * 100).toFixed(1) : 0}%)`, 20, y + 35);
    
    // Department Performance
    if (analyticsData.departmentStats.length > 0) {
      autoTable(doc, {
        startY: y + 50,
        head: [['Department', 'Total', 'Active', 'Completed', 'Rate']],
        body: analyticsData.departmentStats.map(dept => [
          dept.name,
          dept.total.toString(),
          dept.active.toString(),
          dept.completed.toString(),
          `${dept.completionRate}%`
        ]),
        theme: 'grid',
        headStyles: { fillColor: [16, 185, 129] }
      });
    }
    
    doc.save(`Analytics_Report_${date.replace(/\//g, '-')}.pdf`);
  } else {
    // Excel export
    const wb = XLSX.utils.book_new();
    
    // Summary sheet
    const summaryData = [
      ['Analytics Report', ''],
      ['Generated', date],
      ['', ''],
      ['Metric', 'Value'],
      ['Total Projects', analyticsData.totalProjects],
      ['Completed Projects', analyticsData.completedProjects],
      ['Active Projects', analyticsData.activeProjects],
      ['Pending Projects', analyticsData.pendingProjects],
      ['Completion Rate', `${((analyticsData.completedProjects / analyticsData.totalProjects) * 100).toFixed(1)}%`],
      ['Total Budget', `₱${analyticsData.totalBudget.toLocaleString()}`],
      ['Completed Budget', `₱${analyticsData.completedBudget.toLocaleString()}`],
      ['Budget Utilization', `${analyticsData.totalBudget > 0 ? ((analyticsData.completedBudget / analyticsData.totalBudget) * 100).toFixed(1) : 0}%`]
    ];
    const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');
    
    // Department Performance sheet
    if (analyticsData.departmentStats.length > 0) {
      const deptWs = XLSX.utils.json_to_sheet(analyticsData.departmentStats);
      XLSX.utils.book_append_sheet(wb, deptWs, 'Departments');
    }
    
    // Team Performance sheet
    if (analyticsData.teamStats.length > 0) {
      const teamWs = XLSX.utils.json_to_sheet(analyticsData.teamStats);
      XLSX.utils.book_append_sheet(wb, teamWs, 'Team Performance');
    }
    
    XLSX.writeFile(wb, `Analytics_Report_${date.replace(/\//g, '-')}.xlsx`);
  }
};

// ============================================
// PROJECT EXPORT
// ============================================

export const exportProjectsReport = (projects: any[], format: 'pdf' | 'excel') => {
  const columns = [
    { header: 'Project Title', dataKey: 'title', key: 'title', width: 30 },
    { header: 'Status', dataKey: 'status', key: 'status', width: 15 },
    { header: 'Department', dataKey: 'department', key: 'department', width: 20 },
    { header: 'Budget', dataKey: 'budgetFormatted', key: 'budgetFormatted', width: 15 },
    { header: 'Progress', dataKey: 'progressFormatted', key: 'progressFormatted', width: 12 },
    { header: 'Start Date', dataKey: 'startDateFormatted', key: 'startDateFormatted', width: 15 },
    { header: 'End Date', dataKey: 'endDateFormatted', key: 'endDateFormatted', width: 15 }
  ];
  
  const formattedData = projects.map(project => ({
    ...project,
    budgetFormatted: `₱${(project.budget || 0).toLocaleString()}`,
    progressFormatted: `${project.progress || 0}%`,
    startDateFormatted: new Date(project.startDate).toLocaleDateString('en-PH'),
    endDateFormatted: new Date(project.endDate).toLocaleDateString('en-PH')
  }));
  
  if (format === 'pdf') {
    exportToPDF({
      title: 'Projects Report',
      subtitle: `Total Projects: ${projects.length}`,
      data: formattedData,
      columns,
      filename: `Projects_Report_${new Date().toISOString().split('T')[0]}`,
      orientation: 'landscape'
    });
  } else {
    exportToExcel({
      data: formattedData,
      sheetName: 'Projects',
      filename: `Projects_Report_${new Date().toISOString().split('T')[0]}`,
      columns
    });
  }
};

// ============================================
// USER PERFORMANCE EXPORT
// ============================================

export const exportUserPerformanceReport = (users: any[], format: 'pdf' | 'excel') => {
  const columns = [
    { header: 'Name', dataKey: 'name', key: 'name', width: 25 },
    { header: 'Role', dataKey: 'role', key: 'role', width: 15 },
    { header: 'Department', dataKey: 'department', key: 'department', width: 20 },
    { header: 'Level', dataKey: 'level', key: 'level', width: 10 },
    { header: 'XP', dataKey: 'experience', key: 'experience', width: 12 },
    { header: 'Tasks Completed', dataKey: 'totalTasksCompleted', key: 'totalTasksCompleted', width: 15 },
    { header: 'Success Rate', dataKey: 'successRateFormatted', key: 'successRateFormatted', width: 15 }
  ];
  
  const formattedData = users.map(user => ({
    ...user,
    role: user.userLevel?.name || 'N/A',
    successRateFormatted: `${(user.projectSuccessRate || 0).toFixed(1)}%`
  }));
  
  if (format === 'pdf') {
    exportToPDF({
      title: 'User Performance Report',
      subtitle: `Total Users: ${users.length}`,
      data: formattedData,
      columns,
      filename: `User_Performance_${new Date().toISOString().split('T')[0]}`,
      orientation: 'landscape'
    });
  } else {
    exportToExcel({
      data: formattedData,
      sheetName: 'User Performance',
      filename: `User_Performance_${new Date().toISOString().split('T')[0]}`,
      columns
    });
  }
};

// ============================================
// DEPARTMENT STATISTICS EXPORT
// ============================================

export const exportDepartmentReport = (departments: any[], format: 'pdf' | 'excel') => {
  const columns = [
    { header: 'Department', dataKey: 'name', key: 'name', width: 25 },
    { header: 'Category', dataKey: 'category', key: 'category', width: 20 },
    { header: 'Total Projects', dataKey: 'total', key: 'total', width: 15 },
    { header: 'Active', dataKey: 'active', key: 'active', width: 12 },
    { header: 'Completed', dataKey: 'completed', key: 'completed', width: 12 },
    { header: 'Completion Rate', dataKey: 'completionRateFormatted', key: 'completionRateFormatted', width: 15 }
  ];
  
  const formattedData = departments.map(dept => ({
    ...dept,
    completionRateFormatted: `${dept.completionRate}%`
  }));
  
  if (format === 'pdf') {
    exportToPDF({
      title: 'Department Statistics Report',
      subtitle: `Total Departments: ${departments.length}`,
      data: formattedData,
      columns,
      filename: `Department_Report_${new Date().toISOString().split('T')[0]}`
    });
  } else {
    exportToExcel({
      data: formattedData,
      sheetName: 'Departments',
      filename: `Department_Report_${new Date().toISOString().split('T')[0]}`,
      columns
    });
  }
};

// ============================================
// BUDGET REPORT EXPORT
// ============================================

export const exportBudgetReport = (
  budgetData: {
    totalBudget: number;
    totalSpent: number;
    projectBudgets: any[];
  },
  format: 'pdf' | 'excel'
) => {
  const columns = [
    { header: 'Project', dataKey: 'title', key: 'title', width: 30 },
    { header: 'Department', dataKey: 'department', key: 'department', width: 20 },
    { header: 'Budget', dataKey: 'budgetFormatted', key: 'budgetFormatted', width: 15 },
    { header: 'Spent', dataKey: 'spentFormatted', key: 'spentFormatted', width: 15 },
    { header: 'Remaining', dataKey: 'remainingFormatted', key: 'remainingFormatted', width: 15 },
    { header: 'Utilization', dataKey: 'utilizationFormatted', key: 'utilizationFormatted', width: 12 }
  ];
  
  const formattedData = budgetData.projectBudgets.map(project => ({
    ...project,
    budgetFormatted: `₱${(project.budget || 0).toLocaleString()}`,
    spentFormatted: `₱${(project.spent || 0).toLocaleString()}`,
    remainingFormatted: `₱${((project.budget || 0) - (project.spent || 0)).toLocaleString()}`,
    utilizationFormatted: `${project.budget > 0 ? ((project.spent / project.budget) * 100).toFixed(1) : 0}%`
  }));
  
  if (format === 'pdf') {
    const doc = new jsPDF('landscape', 'mm', 'a4');
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(16, 185, 129);
    doc.text('Budget Report', 14, 20);
    
    // Summary
    doc.setFontSize(12);
    let y = 30;
    doc.text(`Total Budget: ₱${budgetData.totalBudget.toLocaleString()}`, 14, y);
    doc.text(`Total Spent: ₱${budgetData.totalSpent.toLocaleString()}`, 14, y + 7);
    doc.text(`Remaining: ₱${(budgetData.totalBudget - budgetData.totalSpent).toLocaleString()}`, 14, y + 14);
    doc.text(`Overall Utilization: ${budgetData.totalBudget > 0 ? ((budgetData.totalSpent / budgetData.totalBudget) * 100).toFixed(1) : 0}%`, 14, y + 21);
    
    // Table
    autoTable(doc, {
      startY: y + 30,
      head: [columns.map(col => col.header)],
      body: formattedData.map(item => columns.map(col => item[col.dataKey] || '-')),
      theme: 'grid',
      headStyles: { fillColor: [16, 185, 129] }
    });
    
    doc.save(`Budget_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  } else {
    const wb = XLSX.utils.book_new();
    
    // Summary sheet
    const summary = [
      ['Budget Report Summary'],
      ['Generated', new Date().toLocaleString('en-PH')],
      [''],
      ['Total Budget', `₱${budgetData.totalBudget.toLocaleString()}`],
      ['Total Spent', `₱${budgetData.totalSpent.toLocaleString()}`],
      ['Remaining', `₱${(budgetData.totalBudget - budgetData.totalSpent).toLocaleString()}`],
      ['Utilization Rate', `${budgetData.totalBudget > 0 ? ((budgetData.totalSpent / budgetData.totalBudget) * 100).toFixed(1) : 0}%`]
    ];
    const summaryWs = XLSX.utils.aoa_to_sheet(summary);
    XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');
    
    // Details sheet
    const detailsWs = XLSX.utils.json_to_sheet(formattedData);
    XLSX.utils.book_append_sheet(wb, detailsWs, 'Project Budgets');
    
    XLSX.writeFile(wb, `Budget_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
  }
};
